# ----------------------------------------
# COMMON
# ----------------------------------------
spring:
  application:
    name: covfefe
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
  datasource:
    data: classpath:data-h2.sql
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

kakao.rest.app.key: 89e2a82c7ca71ece6aeff791d9ed95b2
kakao.rest.api.host: dapi.kakao.com
kakao.rest.api.book.path: /v2/search/book

## App Properties
app.jwtSecret: JWTSuperSecretKey
app.jwtExpirationInMs: 604800000

---

# ----------------------------------------
# DEVELOPMENT
# ----------------------------------------
spring:
  profiles: default, dev
  jpa:
    show-sql: true

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

---

# ----------------------------------------
# PRODUCTION
# ----------------------------------------
spring:
  profiles: prod